apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-deployment
spec:
  selector:
    matchLabels:
      app: go
  replicas: 2
  template:
    metadata:
      labels:
        app: go
    spec:
      containers:
      - name: golang
        image: go-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080