apiVersion: apps/v1
kind: Deployment
metadata:
  name: py-deployment
spec:
  selector:
    matchLabels:
      app: py
  replicas: 3
  template:
    metadata:
      labels:
        app: py
    spec:
      containers:
      - name: python
        image: py-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080